[package]
name = "azure_openai_example_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.105"
dotenv = "0.15"
tokio = { version = "1", features = ["full"] }
