@deploymentName = gpt-4-1106-preview
@apiVersion = 2024-02-15-preview

### ListFiles
GET {{$dotenv AZURE_OPENAI_ENDPOINT}}/openai/files?api-version={{apiVersion}}&purpose=assistants
api-key: {{$dotenv AZURE_OPENAI_KEY}}
Accept: application/json

### GetFile
@fileId = 1

GET {{$dotenv AZURE_OPENAI_ENDPOINT}}/openai/files/{{fileId}}?api-version={{apiVersion}}
api-key: {{$dotenv AZURE_OPENAI_KEY}}
Accept: application/json

### DeleteFile

DELETE {{$dotenv AZURE_OPENAI_ENDPOINT}}/openai/files/{{fileId}}?api-version={{apiVersion}}
api-key: {{$dotenv AZURE_OPENAI_KEY}}
Accept: application/json

