### No streaming
POST {{$dotenv OPENAI_ENDPOINT}}/completions
Content-Type: application/json
Authorization: Bearer {{$dotenv OPENAI_KEY}}
Accept: application/json

{
    "prompt": [
        "Say this is a test"
    ],
    "max_tokens": 100,
    "model": "text-davinci-003"
}

### streaming
POST {{$dotenv OPENAI_ENDPOINT}}/completions
Content-Type: application/json
Authorization: Bearer {{$dotenv OPENAI_KEY}}
Accept: application/json

{
    "prompt": [
        "Say this is a test"
    ],
    "max_tokens": 100,
    "stream": true,
    "model": "text-davinci-003"
}
